### ISSUE TITLE
The link to the Kazakh language corpus on GDrive is broken

### ISSUE THREAD

**Issue by zaitmambet** [chapayevdauren/kazakh-language-corpus#1]
Hi Dauren, is it possible to get access to the language corpus? The link seems to be broken at the moment. Thank you!

**Comment by chapayevdauren** [comment]
Hi @zaitmambet 
Currently, nope I think but you can generate it again easily.

Steps:
- Download Wikipedia dump (https://dumps.wikimedia.org/kkwiki/). 
- Use a WikiExtractor (https://github.com/attardi/wikiextractor) to parse data
- Run [kk_ngrams.py](https://github.com/chapayevdauren/kazakh-language-corpus/blob/master/kk_ngrams.py) script
